### ping
GET http://localhost:61128/customer-user/ping

### encode
GET http://localhost:61128/customer-user/encode/123456

### change password
PUT http://localhost:61128/customer-user/v1.0/en/auth/change-password
Content-Type: application/json

{
  "userId": 1,
  "currentPassword": "123456",
  "newPassword": "1234567"
}

