### ping
GET http://localhost:61128/customer-user/ping


### user profiles
GET http://localhost:61128/customer-user/v1.0/en/users/1/profile


### post user
POST http://localhost:61128/customer-user/v1.0/en/users
Content-Type: application/json

{
  "username": "tester2112021538",
  "password": "123456",
  "email": "tester2112021538@gmail.com",
  "createdActor": "tester2112021538"
}
