POST http://localhost:61127/portal/v1.0/en/auth/sign-up
Content-Type: application/json

{
  "username":"tester56",
  "password":"123456",
  "surname":"Tester5",
  "givenName":"tester5",
  "email":"tester5@gmail.com",
  "birthday":"1998-11-08",
  "gender":1,
  "mobile":"123456"
}

### Login
POST http://localhost:61127/portal/v1.0/en/auth/login
Content-Type: application/json

{
  "username": "PH210325A",
  "password": "123456"
}

### Change password
PUT http://localhost:61127/portal/v1.0/en/auth/change-password
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQSDIxMDMyNUEiLCJpYXQiOjE2MzcwNDM3NDUsImV4cCI6MTcyMzQ0Mzc0NX0.Y7zjkvNf43-2fRISuHEy0di4vJBqcdfjEmaI-hhKorw

{
  "currentPassword": "456",
  "newPassword": "123456"
}
