### PING REQUESET
GET https://gwapi.spmed.kr/api-gateway/v1.0/portal/ping

### LOGIN REQUEST
POST  https://gwapi.spmed.kr/api-gateway/v1.0/portal/v1.0/en/auth/login
Content-Type: application/json

{
  "username": "tester1",
  "password": 123456
}
